# Generated by Django 4.2.2 on 2023-07-03 19:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('password', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=350, null=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Product_Type',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_Cart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bakery.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Bakery.product')),
                ('shopping_cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='Bakery.shopping_cart')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bakery.product_type'),
        ),
        migrations.AddConstraint(
            model_name='shopping_item',
            constraint=models.UniqueConstraint(fields=('shopping_cart', 'product'), name='unique_shopping_cart_product_combination'),
        ),
    ]
