# Generated by Django 4.2.2 on 2023-07-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type',
            name='id',
            field=models.IntegerField(default=0),
        ),
    ]
