# Generated by Django 4.2.2 on 2023-07-29 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0005_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Bakery.product'),
        ),
        migrations.AlterField(
            model_name='shopping_item',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shopping_item',
            name='shopping_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='Bakery.shopping_cart'),
        ),
    ]
