# Generated by Django 4.2.2 on 2023-07-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0006_alter_shopping_item_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_item',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
